version: "3.9"

services:
  backend1:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=development

  backend2:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    ports:
      - "5002:5000"
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0
    command: ["vite", "--host", "0.0.0.0", "--port", "5173"]

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - backend1
      - backend2
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
